// constants/campaigns.js
// Campaign metadata — theme colors, fonts, display names
// Three career routes (internal ids: japanese / korean / spanish map to data folders)
// NEVER use raw hex colors in components — always reference these tokens

export const CAMPAIGN_THEMES = {
  japanese: {
    id: 'japanese',
    name: 'Engineer Ascent',
    name_target: '程序员路线',
    subtitle: 'Ship · Debug · Scale',
    tagline: 'From first commit to last deploy — climb the release train.',
    primary: '#0f172a',
    accent: '#38bdf8',
    accent2: '#f472b6',
    cardVocab: '#ef4444',
    cardGrammar: '#3b82f6',
    cardReading: '#22c55e',
    font: 'JetBrains Mono, ui-monospace, monospace',
    bgGradient: 'linear-gradient(180deg, #020617 0%, #0f172a 45%, #0a0a0a 100%)',
    particleColor: '#38bdf8',
    particleEmoji: '⌨️',
    floors: 4,
    campaignWorld: 'Release train, on-call nights, and the codebase that never sleeps.',
    locked: false,
  },
  korean: {
    id: 'korean',
    name: 'Design Systems Run',
    name_target: 'UI 设计师路线',
    subtitle: 'Layout · Motion · Craft',
    tagline: 'Pixels with opinions — polish the path to launch.',
    primary: '#1a0a2e',
    accent: '#c084fc',
    accent2: '#f472b6',
    cardVocab: '#f472b6',
    cardGrammar: '#a78bfa',
    cardReading: '#34d399',
    font: 'Plus Jakarta Sans, system-ui, sans-serif',
    bgGradient: 'linear-gradient(180deg, #0f0518 0%, #1e1030 50%, #0d0d0d 100%)',
    particleColor: '#c084fc',
    particleEmoji: '🎨',
    floors: 4,
    campaignWorld: 'Design critiques, token libraries, and handoff rituals.',
    locked: false,
  },
  spanish: {
    id: 'spanish',
    name: 'Product Road War',
    name_target: '产品经理路线',
    subtitle: 'Scope · Stakeholders · Delivery',
    tagline: 'Every milestone is a boss fight — alignment is your weapon.',
    primary: '#1c1917',
    accent: '#fb923c',
    accent2: '#2dd4bf',
    cardVocab: '#fb923c',
    cardGrammar: '#2dd4bf',
    cardReading: '#facc15',
    font: 'Source Serif 4, Georgia, serif',
    bgGradient: 'linear-gradient(180deg, #0c0a09 0%, #292524 50%, #0d0d0d 100%)',
    particleColor: '#fb923c',
    particleEmoji: '📊',
    floors: 4,
    campaignWorld: 'Roadmaps, reviews, and the endless backlog horizon.',
    locked: false,
  },
}

export const CARDS = {
  japanese: {
    characters: [
      {
        id: 'kenji',
        job: 'dev',
        name: '程序员',
        title: '',
        description: 'Ship, debug, and scale — from first commit to the release train.',
        startingDeckBreakdown: { attack: 4, skill: 3, power: 2, rare: 1 },
        starterRelic: 'travelers_compass',
        hp: 80,
        locked: false,
      },
      {
        id: 'ren',
        job: 'qa',
        name: '测试工程师',
        title: '质量',
        description: 'Writes repro steps that haunt bugs until they confess.',
        startingDeckBreakdown: { attack: 4, skill: 3, power: 2, rare: 1 },
        starterRelic: 'incident_buffer',
        hp: 80,
        locked: false,
      },
    ],
  },
  korean: {
    characters: [
      {
        id: 'minjun',
        job: 'ui',
        name: '初级设计师',
        title: '新人',
        description: 'Frames problems before pixels. The grid is a moral stance.',
        startingDeckBreakdown: { attack: 4, skill: 3, power: 2, rare: 1 },
        starterRelic: 'brief_rain',
        hp: 80,
        locked: false,
      },
      {
        id: 'jiwoo',
        job: 'ui',
        name: '资深设计师',
        title: '系统',
        description: 'One token to bind them — consistency is the real feature.',
        startingDeckBreakdown: { attack: 4, skill: 3, power: 2, rare: 1 },
        starterRelic: 'grid_snap_ruler',
        hp: 80,
        locked: false,
      },
    ],
  },
  spanish: {
    characters: [
      {
        id: 'mateo',
        job: 'pm',
        name: '产品经理',
        title: '执行',
        description: 'Runs toward ambiguity with a spreadsheet and hope.',
        startingDeckBreakdown: { attack: 4, skill: 3, power: 2, rare: 1 },
        starterRelic: 'syntax_stapler',
        hp: 80,
        locked: false,
      },
      {
        id: 'elena',
        job: 'pm',
        name: '资深产品经理',
        title: '规划',
        description: 'Translates exec intent into tickets the team can actually finish.',
        startingDeckBreakdown: { attack: 4, skill: 3, power: 2, rare: 1 },
        starterRelic: 'handoff_marker',
        hp: 80,
        locked: false,
      },
    ],
  },
}
